CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance decimal(10,2) NOT NULL
);



CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    transaction_group_id UUID NOT NULL,
    amount numeric(10,2) NOT NULL,
    created_date timestamp(6) with time zone NOT NULL
);


ALTER TABLE transactions add constraint fk_transactions_accounts
foreign key (account_id) references accounts (id);
